# Generated by Django 5.2.11 on 2026-02-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_25e057_idx',
            old_name='orders_orde_status_8ffe9c_idx',
        ),
    ]
