# Generated by Django 5.2.11 on 2026-02-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_expires_at_alter_coupon_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Ítem de carrito', 'verbose_name_plural': 'Ítems de carrito'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Cupón', 'verbose_name_plural': 'Cupones'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Ítem de orden', 'verbose_name_plural': 'Ítems de orden'},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'verbose_name': 'Historial de estado de orden', 'verbose_name_plural': 'Historiales de estado de orden'},
        ),
    ]
