# Generated by Django 5.2.11 on 2026-02-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_is_acti_00391f_idx',
            old_name='catalog_pro_is_acti_b8dd35_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='catalog_pro_product_9ec418_idx',
            old_name='catalog_pro_product_6217c7_idx',
        ),
    ]
