# Generated by Django 5.2.11 on 2026-02-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_catalog_pro_is_acti_b8dd35_idx_catalog_pro_is_acti_00391f_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Imágenes de producto'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Variante de producto', 'verbose_name_plural': 'Variantes de producto'},
        ),
    ]
