# Generated by Django 5.2.11 on 2026-02-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_i_variant_b826d6_idx',
            old_name='inventory_i_variant_56b574_idx',
        ),
        migrations.RenameIndex(
            model_name='stocklevel',
            new_name='inventory_s_availab_e3ea7a_idx',
            old_name='inventory_s_availab_7b9ddc_idx',
        ),
    ]
