# Generated by Django 5.2.11 on 2026-02-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_inventory_i_variant_56b574_idx_inventory_i_variant_b826d6_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'verbose_name': 'Movimiento de inventario', 'verbose_name_plural': 'Movimientos de inventario'},
        ),
        migrations.AlterModelOptions(
            name='stocklevel',
            options={'verbose_name': 'Nivel de stock', 'verbose_name_plural': 'Niveles de stock'},
        ),
    ]
