# Generated by Django 5.2.11 on 2026-03-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_address_options_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Panama', max_length=80),
        ),
    ]
